"""add_feedback_settings_to_programs

Revision ID: 486a61019955
Revises: 697fd5744b87
Create Date: 2026-04-12 11:32:13.258452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '486a61019955'
down_revision: Union[str, Sequence[str], None] = '697fd5744b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_email',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_audit_logs_created'), table_name='audit_logs')
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.drop_constraint(op.f('audit_logs_institution_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_avail_blocks_ext'), table_name='availability_blocks')
    op.drop_index(op.f('idx_avail_blocks_time'), table_name='availability_blocks')
    op.drop_index(op.f('idx_avail_blocks_user'), table_name='availability_blocks')
    op.alter_column('feedbacks', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_oauth_states_state'), table_name='oauth_states')
    op.add_column('programs', sa.Column('feedback_enabled', sa.Boolean(), nullable=True))
    op.add_column('programs', sa.Column('feedback_questions', sa.JSON(), nullable=True))
    op.alter_column('programs', 'target_groups',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('programs', 'collision_resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('programs', 'blocked_program_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_programs_archived'), table_name='programs', postgresql_where="(status = 'archived'::text)")
    op.drop_index(op.f('idx_programs_room'), table_name='programs')
    op.create_foreign_key(None, 'programs', 'users', ['archived_by'], ['id'])
    op.drop_index(op.f('idx_refresh_tokens_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_user'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_reservations_collision'), table_name='reservations', postgresql_where="(status <> 'cancelled'::text)")
    op.alter_column('schools', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_cal_integrations_inst'), table_name='user_calendar_integrations')
    op.drop_index(op.f('idx_cal_integrations_user'), table_name='user_calendar_integrations')
    op.drop_constraint(op.f('user_calendar_integrations_user_id_provider_key'), 'user_calendar_integrations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_calendar_integrations_user_id_provider_key'), 'user_calendar_integrations', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_cal_integrations_user'), 'user_calendar_integrations', ['user_id'], unique=False)
    op.create_index(op.f('idx_cal_integrations_inst'), 'user_calendar_integrations', ['institution_id'], unique=False)
    op.alter_column('schools', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_reservations_collision'), 'reservations', ['institution_id', 'date', 'status'], unique=False, postgresql_where="(status <> 'cancelled'::text)")
    op.create_index(op.f('idx_refresh_tokens_user'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.create_index(op.f('idx_programs_room'), 'programs', ['room_id'], unique=False)
    op.create_index(op.f('idx_programs_archived'), 'programs', ['status'], unique=False, postgresql_where="(status = 'archived'::text)")
    op.alter_column('programs', 'blocked_program_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('programs', 'collision_resources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('programs', 'target_groups',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('programs', 'feedback_questions')
    op.drop_column('programs', 'feedback_enabled')
    op.create_index(op.f('idx_oauth_states_state'), 'oauth_states', ['state'], unique=False)
    op.alter_column('feedbacks', 'answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_avail_blocks_user'), 'availability_blocks', ['user_id'], unique=False)
    op.create_index(op.f('idx_avail_blocks_time'), 'availability_blocks', ['user_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_avail_blocks_ext'), 'availability_blocks', ['external_event_id'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_institution_id_fkey'), 'audit_logs', 'institutions', ['institution_id'], ['id'])
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_created'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'user_email',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
