"""add_feedback_settings_to_programs

Revision ID: 486a61019955
Revises: 697fd5744b87
Create Date: 2026-04-12 11:32:13.258452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '486a61019955'
down_revision: Union[str, Sequence[str], None] = '697fd5744b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(bind, table_name: str, column_name: str) -> bool:
    return bool(bind.execute(
        sa.text("""
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table_name
              AND column_name = :column_name
        """),
        {"table_name": table_name, "column_name": column_name},
    ).scalar())


def _table_exists(bind, table_name: str) -> bool:
    return bool(bind.execute(sa.text("SELECT to_regclass(:table_name)"), {"table_name": table_name}).scalar())


def _create_missing_support_tables(bind) -> None:
    """Create support tables that existed in production before this autogenerated migration.

    The original migration was generated against a database that already had
    these tables. A clean regression database reaches this migration without
    them, so we create only this narrow support set from the current metadata.
    """
    from database.models import Base

    table_names = [
        "rooms",
        "audit_logs",
        "feedback_questions",
        "feedbacks",
        "user_calendar_integrations",
        "availability_blocks",
        "refresh_tokens",
        "oauth_states",
    ]
    tables = [
        Base.metadata.tables[name]
        for name in table_names
        if name in Base.metadata.tables and not _table_exists(bind, name)
    ]
    if tables:
        Base.metadata.create_all(bind=bind, tables=tables)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    _create_missing_support_tables(bind)

    # ### commands auto generated by Alembic - adjusted for clean test databases ###
    if _table_exists(bind, "audit_logs"):
        if _column_exists(bind, "audit_logs", "user_email"):
            op.execute("ALTER TABLE audit_logs ALTER COLUMN user_email DROP NOT NULL")
        if _column_exists(bind, "audit_logs", "details"):
            op.execute("ALTER TABLE audit_logs ALTER COLUMN details TYPE JSON USING details::json")
        op.execute("DROP INDEX IF EXISTS idx_audit_logs_created")
        op.execute("CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs (created_at)")
        op.execute("ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_institution_id_fkey")
        op.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_audit_logs_institution_id'
                ) THEN
                    ALTER TABLE audit_logs
                    ADD CONSTRAINT fk_audit_logs_institution_id
                    FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE;
                END IF;
            END $$;
        """)

    op.execute("DROP INDEX IF EXISTS idx_avail_blocks_ext")
    op.execute("DROP INDEX IF EXISTS idx_avail_blocks_time")
    op.execute("DROP INDEX IF EXISTS idx_avail_blocks_user")

    if _table_exists(bind, "feedbacks") and _column_exists(bind, "feedbacks", "answers"):
        op.execute("ALTER TABLE feedbacks ALTER COLUMN answers TYPE JSON USING answers::json")

    op.execute("DROP INDEX IF EXISTS idx_oauth_states_state")

    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS feedback_enabled BOOLEAN")
    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS feedback_questions JSON")
    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS target_groups JSON DEFAULT '[]'::json")
    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS collision_resources JSON DEFAULT '[]'::json")
    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS blocked_program_ids JSON DEFAULT '[]'::json")
    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS archived_by UUID")
    op.execute("ALTER TABLE programs ADD COLUMN IF NOT EXISTS room_id UUID")
    op.execute("DROP INDEX IF EXISTS idx_programs_archived")
    op.execute("DROP INDEX IF EXISTS idx_programs_room")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'fk_programs_archived_by'
            ) THEN
                ALTER TABLE programs
                ADD CONSTRAINT fk_programs_archived_by
                FOREIGN KEY (archived_by) REFERENCES users(id);
            END IF;
        END $$;
    """)

    op.execute("DROP INDEX IF EXISTS idx_refresh_tokens_hash")
    op.execute("DROP INDEX IF EXISTS idx_refresh_tokens_user")
    op.execute("DROP INDEX IF EXISTS idx_reservations_collision")

    op.execute("ALTER TABLE schools ADD COLUMN IF NOT EXISTS tags JSON DEFAULT '[]'::json")
    op.execute("ALTER TABLE schools ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'organic'")
    if _column_exists(bind, "schools", "tags"):
        op.execute("ALTER TABLE schools ALTER COLUMN tags TYPE JSON USING tags::json")

    op.execute("DROP INDEX IF EXISTS idx_cal_integrations_inst")
    op.execute("DROP INDEX IF EXISTS idx_cal_integrations_user")
    op.execute("""
        ALTER TABLE user_calendar_integrations
        DROP CONSTRAINT IF EXISTS user_calendar_integrations_user_id_provider_key
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_calendar_integrations_user_id_provider_key'), 'user_calendar_integrations', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_cal_integrations_user'), 'user_calendar_integrations', ['user_id'], unique=False)
    op.create_index(op.f('idx_cal_integrations_inst'), 'user_calendar_integrations', ['institution_id'], unique=False)
    op.alter_column('schools', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_reservations_collision'), 'reservations', ['institution_id', 'date', 'status'], unique=False, postgresql_where="(status <> 'cancelled'::text)")
    op.create_index(op.f('idx_refresh_tokens_user'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.create_index(op.f('idx_programs_room'), 'programs', ['room_id'], unique=False)
    op.create_index(op.f('idx_programs_archived'), 'programs', ['status'], unique=False, postgresql_where="(status = 'archived'::text)")
    op.alter_column('programs', 'blocked_program_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('programs', 'collision_resources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('programs', 'target_groups',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('programs', 'feedback_questions')
    op.drop_column('programs', 'feedback_enabled')
    op.create_index(op.f('idx_oauth_states_state'), 'oauth_states', ['state'], unique=False)
    op.alter_column('feedbacks', 'answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_avail_blocks_user'), 'availability_blocks', ['user_id'], unique=False)
    op.create_index(op.f('idx_avail_blocks_time'), 'availability_blocks', ['user_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_avail_blocks_ext'), 'availability_blocks', ['external_event_id'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_institution_id_fkey'), 'audit_logs', 'institutions', ['institution_id'], ['id'])
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_created'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'user_email',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
