"""Initial schema with all tables

Revision ID: 697fd5744b87
Revises: 
Create Date: 2026-02-25 21:44:41.640161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697fd5744b87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('psc', sa.Text(), nullable=True),
    sa.Column('ico_dic', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.Text(), nullable=True),
    sa.Column('secondary_color', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('programs_limit', sa.Integer(), nullable=False),
    sa.Column('bookings_monthly_limit', sa.Integer(), nullable=False),
    sa.Column('default_available_days', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('default_time_blocks', sa.JSON(), nullable=True),
    sa.Column('operating_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operating_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_program_duration', sa.Integer(), nullable=True),
    sa.Column('default_program_capacity', sa.Integer(), nullable=True),
    sa.Column('default_target_group', sa.Text(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('locale_settings', sa.JSON(), nullable=True),
    sa.Column('gdpr_settings', sa.JSON(), nullable=True),
    sa.Column('pro_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('ico', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('booking_count', sa.Integer(), nullable=True),
    sa.Column('last_booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schools_email', 'schools', ['email'], unique=False)
    op.create_index('idx_schools_institution', 'schools', ['institution_id'], unique=False)
    op.create_table('theme_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('primary_color', sa.Text(), nullable=True),
    sa.Column('secondary_color', sa.Text(), nullable=True),
    sa.Column('accent_color', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('header_style', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), nullable=True),
    sa.Column('gdpr_consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_institution', 'users', ['institution_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name_cs', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('description_cs', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.Text(), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('target_group', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('send_email_notification', sa.Boolean(), nullable=True),
    sa.Column('available_days', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('time_blocks', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_days_before_booking', sa.Integer(), nullable=True),
    sa.Column('max_days_before_booking', sa.Integer(), nullable=True),
    sa.Column('preparation_time', sa.Integer(), nullable=True),
    sa.Column('cleanup_time', sa.Integer(), nullable=True),
    sa.Column('assigned_lecturer_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_lecturer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_programs_institution', 'programs', ['institution_id'], unique=False)
    op.create_index('idx_programs_status', 'programs', ['status'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('time_block', sa.Text(), nullable=False),
    sa.Column('school_name', sa.Text(), nullable=False),
    sa.Column('group_type', sa.Text(), nullable=False),
    sa.Column('age_or_class', sa.Text(), nullable=True),
    sa.Column('num_students', sa.Integer(), nullable=False),
    sa.Column('num_teachers', sa.Integer(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=False),
    sa.Column('contact_email', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('actual_students', sa.Integer(), nullable=True),
    sa.Column('actual_teachers', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_lecturer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_lecturer_name', sa.Text(), nullable=True),
    sa.Column('assigned_lecturer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), nullable=True),
    sa.Column('gdpr_consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_lecturer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reservations_date', 'reservations', ['date'], unique=False)
    op.create_index('idx_reservations_institution', 'reservations', ['institution_id'], unique=False)
    op.create_index('idx_reservations_program', 'reservations', ['program_id'], unique=False)
    op.create_index('idx_reservations_status', 'reservations', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_status', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.Text(), nullable=True),
    sa.Column('package', sa.Text(), nullable=True),
    sa.Column('billing_cycle', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_institution', 'payments', ['institution_id'], unique=False)
    op.create_index('idx_payments_session', 'payments', ['session_id'], unique=False)
    op.drop_table('Programs')
    op.drop_table('Institucion')
    op.drop_table('Users')
    op.drop_table('Reservation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reservation',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('program_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('school_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('participants_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('time', name=op.f('Reservation_pkey')),
    comment='Rezervace'
    )
    op.create_table('Users',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('Users_pkey')),
    comment='Uživatelé'
    )
    op.create_table('Institucion',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tarif', sa.NUMERIC(), autoincrement=False, nullable=True, comment='pricing'),
    sa.PrimaryKeyConstraint('name', name=op.f('Institucion_pkey')),
    comment='Registrované instituce'
    )
    op.create_table('Programs',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('Programs_pkey')),
    comment='Doprovodné programy'
    )
    op.drop_index('idx_payments_session', table_name='payments')
    op.drop_index('idx_payments_institution', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_reservations_status', table_name='reservations')
    op.drop_index('idx_reservations_program', table_name='reservations')
    op.drop_index('idx_reservations_institution', table_name='reservations')
    op.drop_index('idx_reservations_date', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('idx_programs_status', table_name='programs')
    op.drop_index('idx_programs_institution', table_name='programs')
    op.drop_table('programs')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_institution', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('theme_settings')
    op.drop_index('idx_schools_institution', table_name='schools')
    op.drop_index('idx_schools_email', table_name='schools')
    op.drop_table('schools')
    op.drop_table('institutions')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
