"""add_billing_usage_plan_fields

Revision ID: 94b721cab60e
Revises: ef674389fdbe
Create Date: 2026-04-19 11:40:13.975523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94b721cab60e'
down_revision: Union[str, Sequence[str], None] = 'ef674389fdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('first_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_metrics_feature', 'usage_metrics', ['feature_key'], unique=False)
    op.create_index('idx_usage_metrics_inst_feature', 'usage_metrics', ['institution_id', 'feature_key'], unique=True)
    op.create_index('idx_usage_metrics_institution', 'usage_metrics', ['institution_id'], unique=False)
    op.create_table('billing_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('requested_plan_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_invoice_id', sa.Text(), nullable=True),
    sa.Column('provider_payment_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_orders_institution', 'billing_orders', ['institution_id'], unique=False)
    op.create_index('idx_billing_orders_provider', 'billing_orders', ['provider'], unique=False)
    op.create_index('idx_billing_orders_status', 'billing_orders', ['status'], unique=False)
    op.add_column('institutions', sa.Column('plan_activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('institutions', sa.Column('requested_plan_type', sa.Text(), nullable=True))
    op.add_column('institutions', sa.Column('plan_changed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('institutions', sa.Column('plan_changed_by_superadmin_id', sa.UUID(), nullable=True))
    op.add_column('institutions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('institutions', sa.Column('billing_provider', sa.Text(), nullable=True))
    op.add_column('institutions', sa.Column('billing_external_id', sa.Text(), nullable=True))
    op.add_column('institutions', sa.Column('billing_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'billing_note')
    op.drop_column('institutions', 'billing_external_id')
    op.drop_column('institutions', 'billing_provider')
    op.drop_column('institutions', 'auto_renew')
    op.drop_column('institutions', 'plan_changed_by_superadmin_id')
    op.drop_column('institutions', 'plan_changed_by_user_id')
    op.drop_column('institutions', 'requested_plan_type')
    op.drop_column('institutions', 'plan_activated_at')
    op.drop_index('idx_billing_orders_status', table_name='billing_orders')
    op.drop_index('idx_billing_orders_provider', table_name='billing_orders')
    op.drop_index('idx_billing_orders_institution', table_name='billing_orders')
    op.drop_table('billing_orders')
    op.drop_index('idx_usage_metrics_institution', table_name='usage_metrics')
    op.drop_index('idx_usage_metrics_inst_feature', table_name='usage_metrics')
    op.drop_index('idx_usage_metrics_feature', table_name='usage_metrics')
    op.drop_table('usage_metrics')
    # ### end Alembic commands ###
