"""add_mailing_campaign_tables

Revision ID: ef674389fdbe
Revises: 486a61019955
Create Date: 2026-04-15 11:36:13.252976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef674389fdbe'
down_revision: Union[str, Sequence[str], None] = '486a61019955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('recipient_mode', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=False),
    sa.Column('closing_text', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('content_snapshot', sa.JSON(), nullable=True),
    sa.Column('selection_snapshot', sa.JSON(), nullable=True),
    sa.Column('programs_snapshot', sa.JSON(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mailing_campaigns_institution', 'mailing_campaigns', ['institution_id'], unique=False)
    op.create_index('idx_mailing_campaigns_status', 'mailing_campaigns', ['status'], unique=False)
    op.create_table('mailing_campaign_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['mailing_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_campaign', 'mailing_campaign_programs', ['campaign_id'], unique=False)
    op.create_table('mailing_campaign_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('email_provider_id', sa.Text(), nullable=True),
    sa.Column('matching_reason', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['mailing_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['school_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcr_campaign', 'mailing_campaign_recipients', ['campaign_id'], unique=False)
    op.create_index('idx_mcr_status', 'mailing_campaign_recipients', ['status'], unique=False)
    op.create_table('mailing_recipient_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('program_name', sa.Text(), nullable=True),
    sa.Column('program_target_groups', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['mailing_campaign_recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrp_recipient', 'mailing_recipient_programs', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mrp_recipient', table_name='mailing_recipient_programs')
    op.drop_table('mailing_recipient_programs')
    op.drop_index('idx_mcr_status', table_name='mailing_campaign_recipients')
    op.drop_index('idx_mcr_campaign', table_name='mailing_campaign_recipients')
    op.drop_table('mailing_campaign_recipients')
    op.drop_index('idx_mcp_campaign', table_name='mailing_campaign_programs')
    op.drop_table('mailing_campaign_programs')
    op.drop_index('idx_mailing_campaigns_status', table_name='mailing_campaigns')
    op.drop_index('idx_mailing_campaigns_institution', table_name='mailing_campaigns')
    op.drop_table('mailing_campaigns')
    # ### end Alembic commands ###
